ehsan/ehsan/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings 

app_name='ehsan'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard, name='dashboard'),
    path('foodstuff/', include('foodstuff.urls')),
    path('repository/', include('repository.urls')),
    path('recipe/', include('recipe.urls')),
    path('record/', include('record.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    
    path('calendar', calendar, name='calendar'),
]


urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)  # media
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)  # static

ehsan/recipe/urls.py
from django.urls import path, include
from .views import *

app_name='recipe'

urlpatterns = [
    path('add/', add_recipe, name='add_recipe'),
    path('edit/<int:id>', edit_recipe, name='edit_recipe'),
    path('delete/<int:id>/', delete_recipe, name='delete_recipe'),
    path('', recipe_list, name='recipe_list'),
    path('save_recipe_prices_ajax/', save_recipe_prices_ajax, name='save_recipe_prices_ajax'),
    path('calculator/', recipe_selection, name='recipe_selection'),
    path('upload/<str:date>', upload_file, name='upload_file'),
    path('salereport/<str:date>/', salereport, name='salereport'),

]

ehsan/recipe/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils import timezone

class Recipe(models.Model):
    recipe_id = ShortUUIDField(editable=True,unique=True, length=10, max_length=30, alphabet="abcdefgh12345")
    name = models.CharField(max_length=300)
    ingredients = models.JSONField(default=dict, null=True, blank=True)
    date_created = models.DateField(default=timezone.now)

    def __str__(self):
        return self.name

class RecipePrice(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    recipe_prices = models.JSONField()

    def __str__(self):
        return str(self.created_at)
    
    
class RecipeSaleFile(models.Model):
    created_at = models.DateField(auto_now_add=True)
    date_created = models.DateField(default=timezone.now)
    recipe_prices = models.JSONField()

    def __str__(self):
        return str(self.date_created)    

ehsan/recipe/forms.py
from django import forms
from .models import Recipe
from foodstuff.models import Stuffs

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['recipe_id', 'name']  # اضافه کردن recipe_id به فیلدها
        widgets = {
            'recipe_id': forms.TextInput(attrs={'class': 'form-control'}), 
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }

    labels = {
                'recipe_id': 'شناسه رسپی',
                'name': 'نام غذا',
            }
      
class IngredientForm(forms.Form):
    stuff_name = forms.ModelChoiceField(
        queryset=Stuffs.objects.all(),
        empty_label=None,
        widget=forms.Select(attrs={'class': 'form-control select2'}),
        label='نام ماده اولیه'
    )
    amount = forms.FloatField(
        widget=forms.NumberInput(attrs={'class': 'form-control mt-1', 'placeholder': 'مقدار'}),
        label='مقدار'
    )
    
class RecipeSearchForm(forms.Form):
    recipe_id = forms.ChoiceField(
        choices=[(recipe.recipe_id, recipe.name) for recipe in Recipe.objects.all()],
        label="انتخاب غذا",
        widget=forms.Select(attrs={'class': 'form-control p-4 mt-1 recipe-select select2'})
    )
    quantity = forms.IntegerField(
        label="تعداد",
        min_value=1,
        initial=1,
        widget=forms.NumberInput(attrs={'class': 'form-control mt-1 recipe-quantity'})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['recipe_id'].widget.attrs.update({'data-placeholder': 'انتخاب رسپی', 'dir': 'rtl'})


class UploadFileForm(forms.Form):
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))

ehsan/recipe/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RecipeForm, IngredientForm
from .models import Recipe,RecipePrice
from django.forms import formset_factory
from foodstuff.models import Category, Stuffs, Price # وارد کردن مدل‌های Category و Stuffs
from django.db.models import F
from django.http import JsonResponse
import json
import jdatetime
from datetime import datetime

def add_recipe(request):
    IngredientFormSet = formset_factory(IngredientForm, extra=1)
    if request.method == 'POST':
        recipe_form = RecipeForm(request.POST)
        formset = IngredientFormSet(request.POST, prefix='ingredients')
        if recipe_form.is_valid() and formset.is_valid():
            recipe = recipe_form.save(commit=False)
            
            # Processing ingredients data
            ingredients = {}
            for form in formset:
                stuff_name = form.cleaned_data.get('stuff_name')
                amount = form.cleaned_data.get('amount')
                if stuff_name and amount and amount > 0:  # Check if amount is greater than 0
                    ingredients[stuff_name.stuff_id] = amount
                # You may add additional handling if stuff_name or amount is missing
            
            recipe.ingredients = ingredients
            recipe.save()
            return redirect('recipe:recipe_list')
    else:
        recipe_form = RecipeForm()
        formset = IngredientFormSet(prefix='ingredients')

    categories = Category.objects.all()

    return render(request, 'recipe/add_recipe.html', {
        'recipe_form': recipe_form,
        'formset': formset,
        'categories': categories,
    })

def edit_recipe(request, id):
    recipe = get_object_or_404(Recipe, id=id)
    IngredientFormSet = formset_factory(IngredientForm, extra=0)
    
    if request.method == 'POST':
        recipe_form = RecipeForm(request.POST, instance=recipe)
        formset = IngredientFormSet(request.POST, prefix='ingredients')
        
        if recipe_form.is_valid() and formset.is_valid():
            recipe = recipe_form.save(commit=False)
            ingredients = {}
            
            for form in formset:
                stuff_name = form.cleaned_data.get('stuff_name')
                amount = form.cleaned_data.get('amount')
                
                if stuff_name and amount and amount > 0:  # Check if amount is greater than 0
                    ingredients[stuff_name.stuff_id] = amount
            
            recipe.ingredients = ingredients
            recipe.save()
            return redirect('recipe:recipe_list')
    else:
        recipe_form = RecipeForm(instance=recipe)
        initial_data = [{'stuff_name': Stuffs.objects.get(stuff_id=stuff_id), 'amount': amount} for stuff_id, amount in recipe.ingredients.items() if amount > 0]
        formset = IngredientFormSet(initial=initial_data, prefix='ingredients')

    categories = Category.objects.all()

    return render(request, 'recipe/edit_recipe.html', {
        'id': id,
        'recipe_form': recipe_form,
        'formset': formset,
        'categories': categories,
    })

    
def delete_recipe(request, id):
    recipe = get_object_or_404(Recipe, id=id)
    recipe.delete()
    return redirect('recipe:recipe_list')
    
    
def recipe_list(request):
    recipes = Recipe.objects.all()
    prices_list = []

    # خواندن آخرین رکورد قیمت برای هر ماده اولیه و ایجاد یک دیکشنری
    latest_price_record = Price.objects.latest('date')
    latest_prices = latest_price_record.prices    
    
    for recipe in recipes:
        total_price = 0
        ingredients = recipe.ingredients
        
        # تبدیل رشته JSON به دیکشنری در صورت لزوم
        if isinstance(ingredients, str):
            ingredients = json.loads(ingredients)

        for stuff_id, quantity in ingredients.items():
            # بدست آوردن قیمت ماده اولیه از دیکشنری قیمت‌ها
            ingredient_price = float(latest_prices.get(stuff_id, 0))
            # محاسبه قیمت هر ماده اولیه با توجه به تعداد مورد استفاده
            total_price += quantity * ingredient_price
        try:
            recipe_prices_data = RecipePrice.objects.latest('created_at')
            jalali_standard_price_data = jdatetime.date.fromgregorian(date=recipe_prices_data.created_at).strftime('%Y/%m/%d')
            percentage_difference = ((total_price - get_standard_price(recipe.id)) / get_standard_price(recipe.id)) * 100 if get_standard_price(recipe.id) else 0
        except:
            jalali_standard_price_data =''
            percentage_difference = ''
            
        jalali_price_date = jdatetime.date.fromgregorian(date=latest_price_record.date).strftime('%Y/%m/%d')

        # اضافه کردن اطلاعات به لیست
        prices_list.append({
            'recipe_id': recipe.recipe_id,
            'id': recipe.id,            
            'name': recipe.name,
            'total_price': total_price,
            'standard_price': get_standard_price(recipe.id),  # اضافه کردن قیمت معیار
            'percentage_difference': percentage_difference,
        })

    return render(request, 'recipe/recipe_list.html', {'prices_list': prices_list,'jalali_price_date': jalali_price_date,'jalali_standard_price_data': jalali_standard_price_data,})

def get_standard_price(recipe_id):
    # اینجا قیمت معیار را از مدل RecipePrice بر اساس recipe_id بخوانید و برگردانید
    try:
        recipe_prices_data = RecipePrice.objects.latest('created_at').recipe_prices
        recipe_prices_dict = json.loads(recipe_prices_data)
        for recipe_price in recipe_prices_dict:
            if recipe_price['id'] == recipe_id:
                return recipe_price['total_price']
        return ''
    except RecipePrice.DoesNotExist:
        return ''
    
import json
from django.http import JsonResponse
from .models import RecipePrice
import json
from django.http import JsonResponse
from django.utils import timezone
from .models import RecipePrice

def save_recipe_prices_ajax(request):
    recipe_prices_data = request.POST.get('recipe_prices')
    try:
        # Decode JSON data
        recipe_prices_dict = json.loads(recipe_prices_data)

        # Ensure the JSON data is properly encoded
        recipe_prices_json = json.dumps(recipe_prices_dict, ensure_ascii=False)

        # Get today's date
        today = timezone.now().date()

        # Check if a record for today exists
        recipe_price_record = RecipePrice.objects.filter(created_at__date=today).first()

        if recipe_price_record:
            # Update the existing record
            recipe_price_record.recipe_prices = recipe_prices_json
            recipe_price_record.save()
        else:
            # Create a new record
            RecipePrice.objects.create(recipe_prices=recipe_prices_json)

        return JsonResponse({'success': True})
    except json.JSONDecodeError as e:
        return JsonResponse({'success': False, 'error': str(e)})

from .forms import RecipeSearchForm
# views.py
from django.http import JsonResponse

def recipe_selection(request):
    if request.method == 'POST' and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        form = RecipeSearchForm(request.POST)
        if form.is_valid():
            recipe_id = form.cleaned_data['recipe_id']
            quantity = form.cleaned_data['quantity']
            
            recipe = Recipe.objects.get(recipe_id=recipe_id)
            ingredients = recipe.ingredients
            total_ingredients = {}

            for stuff_id, amount in ingredients.items():
                if stuff_id in total_ingredients:
                    total_ingredients[stuff_id] += amount * quantity
                else:
                    total_ingredients[stuff_id] = amount * quantity

            ingredients_details = {Stuffs.objects.get(stuff_id=key).stuff_name: value for key, value in total_ingredients.items()}

            return JsonResponse({'success': True, 'recipe': recipe.name, 'quantity': quantity, 'ingredients_details': ingredients_details})

        return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = RecipeSearchForm()

    return render(request, 'recipe/recipe_selection.html', {'form': form})


import pandas as pd
from django.core.files.storage import FileSystemStorage
from .models import RecipeSaleFile
from .forms import UploadFileForm
from django.utils.timezone import now
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import render, redirect,HttpResponse
import numpy as np

def upload_file(request, date):
    date_obj = datetime.strptime(date, '%Y-%m-%d').date()
    
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            fs = FileSystemStorage()
            filename = fs.save(file.name, file)
            file_path = fs.path(filename)
            
            # خواندن فایل اکسل
            try:
                df = pd.read_excel(file_path, header=0, dtype={
                    'كد كالا': str,           # تمام کد کالاها به عنوان رشته خوانده شوند
                    'مقدار - تعداد': float   # ستون مقدار - تعداد به عنوان اعشاری (float) خوانده شود
                })                
                messages.success(request, 'فایل با موفقیت بارگذاری شد.')
            except Exception as e:
                form.add_error(None, f"Error reading Excel file: {str(e)}")
                return render(request, 'recipe/upload.html', {'form': form})

            # بررسی و به‌روزرسانی یا ایجاد رکورد جدید با اعتبارسنجی
            extracted_data = []
            for index, row in df.iterrows():
                if not pd.isnull(row['كد كالا']) and not pd.isnull(row['نام كالا']) and not pd.isnull(row['مقدار - تعداد']):
                    item = {
                        'code': str(row['كد كالا']),
                        'product_name': row['نام كالا'],

ehsan/templates/recipe/edit_recipe.html
{% extends 'main/main.html' %}
{% load static %}
{% block contant %}
<style>
    .small-td {
        width: 15%;
    }

    .th {
        background-color: #6CC3DA !important;
        color: white !important;
        font-weight: bold !important;
        font-size: 18px !important;
    }

    .customtable {
        font-weight: bold !important;
        font-size: large;
    }

    .price-input {
        padding: 3px !important;
        background-color: #E4F4F8;
        border-color: #E4F4F8;
        font-size: larger;
    }

    .table-responsive {
        height: 600px;
        overflow-y: auto;
        direction: ltr;
    }

    .search-container {
        display: inline-block;
    }

    .table-responsive table {
        direction: rtl;
    }

    .form-control-sm {
        border-color: white !important;
    }

    .btn-arrow {
        background-color: #FF8A00;
        color: white;
        width: 1%;
        height: 1%;
        padding: 1%;
    }

    .form-group {
        margin-bottom: 20px;
        /* فاصله بین فیلدها */
    }
</style>
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold pt-3 mb-4">
        <span class="text-muted fw-light">رسپی/</span> افزودن رسپی
    </h4>
    <div class="card mb-4" style="background-color: #c1e4ea; margin: 20px; box-shadow: none;">
        <div class="card-header" style="margin-inline: 60px;"></div>
        <div class="card-body">
            <div class="card mb-4" style="margin-inline: 60px; box-shadow: none;">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="row" style="align-items: center;">
                            <div class="col-md-1 form-group text-center">
                                <span>آیدی:</span>
                            </div>
                            <div class="col-md-3 form-group" style="margin-right: -30px;">
                                {{ recipe_form.recipe_id }}
                            </div>
                            <div class="col-md-1 form-group text-center">
                                <span style="margin-left: -30px;">نام غذا:</span>
                            </div>
                            <div class="col-md-7 form-group">
                                {{ recipe_form.name }}
                            </div>
                        </div>
                        <hr>
                        <div id="ingredient-forms">
                            {{ formset.management_form }}
                            <div class="row">
                                {% for form in formset %}
                                <div class="col-md-3 ingredient-form form-group">
                                    {{ form.stuff_name }}
                                    {{ form.amount }}
                                </div>
                                {% if forloop.counter|divisibleby:4 and not forloop.last %}
                            </div>
                            <div class="row">
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        <button type="button" id="add-ingredient" class="btn btn-secondary">افزودن ماده اولیه</button>
                        <div class="card-footer text-muted">
                            {{ form.errors }}
                            <a href="#" onclick="window.history.go(-1); return false;"
                                class="btn btn-outline-secondary">انصراف</a>
                            <button type="submit" class="btn btn-primary">ذخیره</button>
                        </div>
                    </form>
                    <form method="post" action="{% url 'recipe:delete_recipe' id %}" style="display:inline;float: left;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger" onclick="return confirm('آیا مطمئن هستید که می‌خواهید این رسپی را حذف کنید؟');">حذف</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            var table = $('#datatable').DataTable({
                paging: false,
                dom: 'lrtip', // remove the default search box
                fixedHeader: {
                    header: true,
                    footer: true
                },
                paging: false,
                scrollCollapse: true,
                scrollX: true,
                scrollY: 380
            });
            $('#search-box').on('keyup', function () {
                table.search(this.value).draw();
            });
            $('.dataTables_info').css('display', 'none');
        });
    </script>
</div>
{% endblock %}
{% block pagejs %}

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function () {
        $('.select2').select2({
            width: '100%'
        });

        let form_idx = {{ formset.total_form_count }};

    $('#add-ingredient').click(function () {
        let new_form = $('#ingredient-forms .ingredient-form:first').clone();

        if (new_form.find('.select2').length) {
            new_form.find('select').select2('destroy');
        }

        new_form.find('input, select').each(function () {
            let name = $(this).attr('name').replace(/\d+/, form_idx);
            let id = $(this).attr('id').replace(/\d+/, form_idx);
            $(this).attr({ 'name': name, 'id': id }).val('');
        });

        let current_row = $('#ingredient-forms .row').last();
        if (current_row.children().length >= 4) {
            current_row = $('<div class="row"></div>').appendTo('#ingredient-forms');
        }

        new_form.appendTo(current_row);

        new_form.find('.select2').select2({
            width: '100%'
        });

        form_idx++;
        updateManagementForm(form_idx);
    });

    function updateManagementForm(count) {
        $('#id_ingredients-TOTAL_FORMS').val(count);
    }
    });
</script>
{% endblock %}

ehsan/templates/recipe/recipe_list.html
{% extends 'main/main.html' %}
{% load static %}
{% load humanizelib %}
{% block contant %}
<style>
    .small-td {
        width: 15%;
    }

    .th {
        background-color: #6CC3DA !important;
        color: white !important;
        font-size: 1vw !important;
        position: -webkit-sticky;
        position: sticky;
        top: 0;
        z-index: 2;
        text-align-last: center; 
        letter-spacing:0px !important;
    }
    .th span{
        font-size: 10px !important;
    }

    .customtable {
        font-weight: bold !important;
        font-size: large;
    }

    .price-input {
        padding: 3px !important;
        background-color: #E4F4F8;
        border-color: #E4F4F8;
        font-size: larger;
    }

    .search-container {
        display: inline-block;
        /* margin-left: 10px; */
    }

    .table-responsive table {
        direction: rtl;
        /* تنظیم جهت محتویات جدول به راست */
    }

    .form-control-sm {
        border-color: white !important;
    }

    .btn-arrow {
        background-color: #FF8A00;
        color: white;
        width: 1%;
        height: 1%;
        padding: 1%;
    }
    .bt-in {
        background-color: #c1e4ea;
        padding: 30px;
        margin-bottom: -30px;
        font-weight: bold;
        font-size: 1vw;
        border-top-left-radius: 15px;
        border-top-right-radius: 15px;
        border-bottom-left-radius: -15px;
        width: 100%;
        text-align: center;
    }

    .bt-in a {
        color: black !important;
    }

    .bt-out {
        padding: 30px;
        margin-bottom: -30px;
        font-weight: bold;
        font-size: 1vw;
        border-top-left-radius: 15px;
        border-top-right-radius: 15px;
        width: 100%;
        text-align: center;
    }

    .bt-out a {
        color: black !important;
    }  
    
</style>
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold pt-3 mb-4">
        <span class="text-muted fw-light">رسپی/</span> غذاها
    </h4>
    <div class="row mb-4" style="justify-content: center;">
        <div class="col-md-6">
            <div class="bt-in">
                <a href="{% url 'recipe:recipe_list'%}" id="inputBtn">گزارش رسپی</a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="bt-out">
                <a href="{% url 'recipe:recipe_selection'%}" id="outputBtn">محاسبه مواد اولیه</a>
            </div>
        </div>
    </div>
    <div class="card mb-4" style="background-color: #c1e4ea; box-shadow: none;margin-top:-20px">
        <div class="card-header" style="margin-inline: 60px;">
            <a href="{% url 'recipe:add_recipe' %}" class="btn btn-primary" style="float: left;"> افزودن رسپی جدید</a>
            <button id="save-recipe-prices-btn" class="btn btn-primary" style="float: left; margin-left: 0.5rem;">ثبت به عنوان معیار</button>
            <div id="datatable_filter" class="form-control-sm search-container">
                <input type="search" id="search-box" placeholder="جستجو" class="form-control form-control-sm">
            </div>
        </div>
        <div class="card-body">
            <div class="card mb-4" style="margin-inline: 60px; box-shadow: none;">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="datatable" class="table table-striped text-center">
                            <thead class="table-light">
                                <tr>
                                    <th style="border-bottom-right-radius: 10px;
                                        border-top-right-radius: 10px; "class="th">کد</th>
                                    <th class="th">نام غذا</th>
                                    <th class="th">قیمت فعلی <span>{{jalali_price_date}}</span></th> <!-- اضافه کردن ستون برای نمایش قیمت -->
                                    <th class="th">قیمت معیار<span>{{jalali_standard_price_data}}</span></th> <!-- اضافه کردن ستون برای نمایش قیمت -->
                                    <th class="th">اختلاف</th> <!-- اضافه کردن ستون برای نمایش قیمت -->
                                    <th style="border-bottom-left-radius: 10px;
                                        border-top-left-radius: 10px; "class="th" style="border-left: 20px !important;">ویرایش</th>
                                </tr>
                            </thead>
                            <tbody id="table-body">
                                {% for price_entry in prices_list %}
                                <tr>
                                    <td class="small-td">{{ price_entry.recipe_id }}</td>
                                    <td class="larege">{{ price_entry.name }}</td>
                                    <td class="large" style="font-size: large;">{{ price_entry.total_price|floatformat:0|intcomma }}</td> <!-- نمایش قیمت کل -->
                                    <td class="larege" style="font-size: large;">{{ price_entry.standard_price|intcomma }}</td> <!-- نمایش قیمت معیار -->
                                    <td class="small-td" style="direction:ltr">{{ price_entry.percentage_difference|floatformat:2|intcomma }}</td>
                                    <td class="small-td">
                                        <a href="{% url 'recipe:edit_recipe' price_entry.id %}" class="mdi mdi-pencil"></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'vendor/js/jquery.min.js' %}"></script>

    <script src="{% static 'vendor/js/dataTables.min.js' %}"></script>


    <script>
        $(document).ready(function () {
            var table = $('#datatable').DataTable({
                paging: false,
                dom: 'lrtip', // remove the default search box
                pageResize: true,
                fixedHeader: {
                    header: true,
                    footer: true
                },
                paging: false,
                scrollCollapse: true,
                scrollX: true,
                scrollY: 458,
            });
            $('#categoryFilter').on('change', function () {
                var category = $(this).val();
                table.column(1).search(category).draw();
            });
            $('#search-box').on('keyup', function () {
                table.search(this.value).draw();
            });
            $('.dataTables_info').css('display', 'none');
        });
    </script>

<script>
    $(document).ready(function () {
        $('#save-recipe-prices-btn').on('click', function (e) {
            e.preventDefault(); // جلوگیری از ارسال فرم به صورت پیش‌فرض

            // تایید از کاربر
            var confirmation = confirm('آیا مطمئن هستید که می‌خواهید قیمت معیار را بروزرسانی کنید؟');
            if (!confirmation) {
                return; // اگر کاربر تایید نکرد، تابع را ترک کنید
            }

            // ادامه فرآیند اگر کاربر تایید کرد
            var recipePricesData = JSON.stringify({{ prices_list|safe }});
            $.ajax({
                type: 'POST',
                url: '{% url "recipe:save_recipe_prices_ajax" %}',
                data: {
                    'recipe_prices': recipePricesData,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                dataType: 'json',
                success: function (response) {
                    if (response.success) {
                        // صفحه را مجدداً بارگذاری کنید
                        location.reload();
                    } else {
                        alert('خطایی در هنگام ثبت قیمت‌ها رخ داده است.');
                    }
                },
                error: function (xhr, status, error) {
                    console.error(xhr.responseText);
                    alert('خطایی در هنگام ثبت قیمت‌ها رخ داده است.');
                }
            });
        });
    });
</script>
</div>
{% endblock %}

ehsan/templates/recipe/upload.html
{% extends 'main/main.html' %}
{% load static %}
{% block contant %}
<style>
    .small-td {
        width: 15%;
    }

    .th {
        background-color: #6CC3DA !important;
        color: white !important;
        font-size: 1vw !important;
        position: -webkit-sticky;
        position: sticky;
        top: 0;
        z-index: 2;
        text-align-last: center;
    }

    /* .customtable {
        font-weight: bold !important;
        font-size: large;
    } */

    .price-input {
        padding: 3px !important;
        border-color: black 20px;
        font-size: larger;
    }

    #table-body {
        font-size: 0.9vw !important;
    }

    .search-container {
        display: inline-block;
        /* margin-left: 10px; */
    }

    .table-responsive {
        direction: rtl;
    }

    .form-control-sm {
        border-color: white !important;
    }

    .btn-arrow {
        background-color: #FF8A00;
        color: white;
        width: 0.2vw;
    }

    /* Styles to reduce row height */
    .table-striped td {
        padding: 4px !important;
        /* Adjust the padding as needed */
        font-size: 0.8vw;
        /* Adjust the font size if needed */
    }

    .table-striped tr {
        line-height: 1 !important;
        /* Reduce the line height */
    }
</style>
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold pt-3 mb-4">
        <span class="text-muted fw-light">رسپی/</span> آپلود فایل گزارش ثبت فروش
    </h4>
    <div class="card mb-4" style="background-color: #c1e4ea; box-shadow: none;">
        <div class="card-header" style="margin-inline: 60px;">
    
        </div>
        <div class="card-body">
            <div class="card mb-4" style="margin-inline: 60px; box-shadow: none;">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-primary mt-4" type="submit">بارگذاری</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}