ehsan/ehsan/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings 

app_name='ehsan'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard, name='dashboard'),
    path('foodstuff/', include('foodstuff.urls')),
    path('repository/', include('repository.urls')),
    path('recipe/', include('recipe.urls')),
    path('record/', include('record.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    
    path('calendar', calendar, name='calendar'),
]


urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)  # media
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)  # static

ehsan/foodstuff/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name='foodstuff'

urlpatterns = [
    # path('', foodstuffs , name='foodstuffs'),
    path('add', addfoodstuffs , name='addfoodstuffs'),
    path('edit-stuff/<str:id>/', edit_stuff, name='edit_stuff'),
    
    path('price/<str:date>/', add_price, name='add_price'),
    path('delete/<int:id>/', delete_stuff, name='delete_stuff'),

]

ehsan/foodstuff/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.contrib.postgres.fields import JSONField
from django.utils import timezone


SCALE = [
    ("Weight", "وزن (کیلوگرم)"),
    ("Number", "عدد (تعداد)"),
] 

class Category(models.Model):
    cat_id = ShortUUIDField(unique=True , length=10 , max_length=30 , alphabet="abcdefgh12345")
    cat_name = models.CharField(max_length = 300)

    def __str__(self):
         return self.cat_name


class Stuffs(models.Model):
    stuff_id = ShortUUIDField(unique=True , length=10 , max_length=30 , alphabet="abcdefgh12345")
    stuff_name = models.CharField(max_length = 300)
    stuff_category = models.ForeignKey(Category, related_name='stuffs', on_delete=models.CASCADE)
    stuff_scale = models.CharField(choices=SCALE , max_length=20 , default="Weight")

    def __str__(self):
         return self.stuff_name


class Price(models.Model):
    id = ShortUUIDField(primary_key=True)
    date = models.DateField(default=timezone.now)
    prices = models.JSONField(default=dict, null=True,blank=True)

    def __str__(self):
        return f"Prices for {self.date}"

ehsan/foodstuff/forms.py
from django import forms
from .models import Stuffs, Category,Price

class StuffsForm(forms.ModelForm):
    class Meta:
        model = Stuffs
        fields = ['stuff_id','stuff_name', 'stuff_category', 'stuff_scale']
        widgets = {
            'stuff_id':forms.TextInput(attrs={'class': 'form-control'}), 
            'stuff_name': forms.TextInput(attrs={'class': 'form-control'}),
            'stuff_category': forms.Select(attrs={'class': 'form-select'}),
            'stuff_scale': forms.Select(attrs={'class': 'form-select'}),
        }

class PriceForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(PriceForm, self).__init__(*args, **kwargs)
        stuffs = Stuffs.objects.all()
        for stuff in stuffs:
            self.fields[f'stuff_{stuff.stuff_id}'] = forms.CharField(
                label=stuff.stuff_name, required=False, widget=forms.TextInput(attrs={'class': 'price-input'})
            )
            
    def clean(self):
        cleaned_data = super(PriceForm, self).clean()
        prices = {}
        for field_name, value in cleaned_data.items():
            if field_name.startswith('stuff_'):
                stuff_id = field_name.split('_')[1]
                # Remove commas before saving to the database
                prices[stuff_id] = value.replace(',', '')
        cleaned_data['prices'] = prices
        return cleaned_data

ehsan/foodstuff/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import StuffsForm ,PriceForm
from .models import Stuffs ,Category, Price
from django.utils import timezone
import jdatetime
from datetime import datetime
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# def foodstuffs(request):
#     stuffs = Stuffs.objects.all()
#     last_price = Price.objects.latest('date')
#     last_price_jalali = jdatetime.date.fromgregorian(date=last_price.date).strftime('%Y/%m/%d')
#     return render(request, 'foodstuff/table-foodstuffs.html', {'stuffs': stuffs, 'last_price_jalali': last_price_jalali})

def addfoodstuffs(request):
    today_date = datetime.today().strftime('%Y-%m-%d')
    categories = Category.objects.all()
    if request.method == "POST":
        form = StuffsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('foodstuff:add_price', kwargs={'date': today_date}))
    else:
        form = StuffsForm()
    
    return render(request, 'foodstuff/add-foodstuffs.html', {'categories': categories,'form': form})

def edit_stuff(request, id):
    today_date = datetime.today().strftime('%Y-%m-%d')
    stuff = get_object_or_404(Stuffs, id=id)
    if request.method == "POST":
        form = StuffsForm(request.POST, instance=stuff)
        if form.is_valid():
            form.save()
            return redirect(reverse('foodstuff:add_price', kwargs={'date': today_date}))
    else:
        form = StuffsForm(instance=stuff)
    return render(request, 'foodstuff/edit_stuff.html', {'form': form ,'id':id})


from django.shortcuts import render, redirect
from .models import Price, Stuffs
from .forms import PriceForm


from datetime import datetime
from django.shortcuts import render, redirect
import jdatetime
from .forms import PriceForm
from .models import Price, Stuffs, Category

def add_price(request, date):
    try:
        price_instance = Price.objects.get(date=date)
        initial_data = {f'stuff_{stuff_id}': price for stuff_id, price in price_instance.prices.items()}
        print(initial_data)
    except:
        price_instance = None  # اختصاص دادن مقدار پیش‌فرض به price_instance
        initial_data = {}
        
    # Find the latest price record before the specified date
    if initial_data == {}:
        latest_price = Price.objects.filter(date__lt=date).order_by('-date').first()
        if latest_price:
            initial_data = {f'stuff_{stuff_id}': price for stuff_id, price in latest_price.prices.items()}
        else :
            initial_data = {f'stuff_{stuff.stuff_id}': '0' for stuff in Stuffs.objects.all()}
    
    if request.method == 'POST':
        form = PriceForm(request.POST, initial=initial_data)
        if form.is_valid():
            prices = form.cleaned_data['prices']
            if price_instance:
                price_instance.prices = prices
                price_instance.save()
            else:
                price_instance = Price.objects.create(date=date, prices=prices)

            # Get today's date
            today_date = datetime.now().strftime('%Y-%m-%d')
            return redirect(f'/foodstuff/price/{today_date}/')
    else:
        form = PriceForm(initial=initial_data)

    gregorian_date = datetime.strptime(date, '%Y-%m-%d')
    jalali_date = jdatetime.date.fromgregorian(date=gregorian_date).strftime('%Y/%m/%d')
    
    # Fetch all stuffs with related category and scale
    stuffs = Stuffs.objects.select_related('stuff_category').all()
    categories = Category.objects.all().order_by('cat_id')  # اضافه کردن دسته بندی‌ها

    return render(request, 'foodstuff/add_price.html', {
        'form': form,
        'jalali_date': jalali_date,
        'date': date,
        'stuffs': stuffs,
        'categories': categories,
    })
    
    
def delete_stuff(request, id):
    today_date = datetime.today().strftime('%Y-%m-%d')
    stuff = get_object_or_404(Stuffs, id=id)
    stuff.delete()
    return redirect(reverse('foodstuff:add_price', kwargs={'date': today_date}))
        

ehsan/templates/foodstuff/add-foodstuffs.html
{% extends 'main/main.html' %}
{% load static %}
{% block contant %}
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold pt-3 mb-4">
    <span class="text-muted fw-light">مواد غذایی/</span> افزودن
  </h4>
  <div class="row">
    <!-- برچسب شناور (طرح حاشیه دار) -->
    <form method="post">
      {% csrf_token %}
      <div class="container mt-4">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-md-3">
                <div class="mt-2 mb-3">
                  <label for="stuff_name" class="stuff_name">نام
                  </label>
                  {{ form.stuff_id }}
                </div>
              </div>
              <div class="col-md-3">
                <div class="mt-2 mb-3">
                  <label for="defaultFormControlInput" class="form-label">نام
                  </label>
                  <input type="text" name="stuff_name" class="form-control" id="defaultFormControlInput"
                    placeholder="ماده غذایی" aria-describedby="defaultFormControlHelp">
                </div>
              </div>
              <div class="col-md-3">
                <div class="mt-2 mb-3">
                  <label for="largeSelect1" class="form-label">دسته بندی</label>
                  <select name="stuff_category" id="largeSelect1" class="form-select">
                    {% for category in categories %}
                    <option value="{{ category.pk }}">{{ category.cat_name }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <div class="col-md-3">
                <div class="mt-2 mb-3">
                  <label for="largeSelect2" class="form-label">واحد اندازه‌گیری</label>
                  <select name="stuff_scale" id="largeSelect2" class="form-select">
                    <option value="Weight">وزن(کیلوگرم)</option>
                    <option value="Number">(عدد)تعداد</option>
                  </select>
                </div>
              </div>
            </div>
          </div>
          <div class="card-footer text-muted">
            {{form.errors}}
            <button type="submit" class="btn btn-primary">ذخیره</button>
            <a href="#" onclick="window.history.go(-1); return false;" class="btn btn-outline-secondary">انصراف</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
<!-- / Content -->
{% endblock %}

ehsan/templates/foodstuff/edit_stuff.html
{% extends 'main/main.html' %}
{% load static %}
{% block contant %}
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold pt-3 mb-4">
    <span class="text-muted fw-light">مواد غذایی/</span> افزودن
  </h4>
  <div class="row">
    <!-- برچسب شناور (طرح حاشیه دار) -->
   
        <div class="container mt-4">
            <div class="card mb-4">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                    <div class="row">
                        <div class="col-md-3">
                            <div class="mt-2 mb-3">
                                <label for="stuff_id" class="form-label">آیدی ماده غذایی</label>
                                {{ form.stuff_id }}
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="mt-2 mb-3">
                                <label for="defaultFormControlInput" class="form-label">نام</label>
                                {{ form.stuff_name }}
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="mt-2 mb-3">
                                <label for="largeSelect1" class="form-label">دسته بندی</label>
                                {{ form.stuff_category }}
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="mt-2 mb-3">
                                <label for="largeSelect2" class="form-label">واحد اندازه‌گیری</label>
                                {{ form.stuff_scale }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-muted row">
                    <div class="col-11">
                        {{ form.errors }}
                        <button type="submit" class="btn btn-primary">ذخیره</button>
                        <a href="#" onclick="window.history.go(-1); return false;" class="btn btn-outline-secondary">انصراف</a>    
                    </div>
                    
                </form>
                <div class="col-1">
                    <form method="post" action="{% url 'foodstuff:delete_stuff' id %}" >
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger" onclick="return confirm('آیا مطمئن هستید که می‌خواهید این ماده غذایی را حذف کنید؟');">حذف</button>
                    </form>    
                </div>
                </div>
            </div>
        </div>
  </div>
</div>
<!-- / Content -->
{% endblock %}

ehsan/templates/foodstuff/table-foodstuffs.html
{% extends 'main/main.html' %}
{% load static %}
{% block contant %}
<style>
  .card-main {
    background-color: #c1e4ea !important;
  }
</style>
<!-- Content -->
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold pt-3 mb-4">
    <span class="text-muted fw-light">مواد غذایی/</span>مشاهده
  </h4>
  <!-- DataTable with Buttons -->
  <!-- <div class="card card-main">
    <div class="card-body"> -->
  <div class="card">
    <div class="card-header">
      <a href="{% url 'foodstuff:addfoodstuffs'%}" class="btn btn-primary" style="float:left;"> افزودن ماده غذایی
        جدید</a>
        <button class="btn btn-secondry" style="float:left; margin-left: 5px;">آخرین به‌روزرسانی قیمت: {{ last_price_jalali }}</button>

      <button class="btn btn-primary" id="submitBtn">برو به قیمت تاریخ</button>
      <input type="date" id="date" name="date" value="{% now 'Y-m-d' %}">
    </div>
    <div class="card-datatable table-responsive pt-0">
      <table id="datatable " class="table-hover table">
        <thead class="table-light">
          <tr>
            <th></th>
            <th>عنوان</th>
            <th>دسته بندی</th>
            <th>مقیاس</th>
            <th>ویرایش</th>
          </tr>
        </thead>
        <tbody id="table-body">
          {% for stuff in stuffs %}
          <tr>
            <td></td>
            <td>{{ stuff.stuff_name }}</td>
            <td>{{ stuff.stuff_category }}</td>
            <td>{{ stuff.get_stuff_scale_display }}</td>
            <td><a href="{% url 'foodstuff:edit_stuff' stuff.id %}">ویرایش</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <!-- / Content -->
  <!-- Content wrapper -->
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      var dateInput = document.getElementById('date');
      var submitBtn = document.getElementById('submitBtn');

      // چک کردن مقدار اولیه تاریخ و تنظیم مقدار پیش‌فرض اگر تاریخی انتخاب نشده باشد
      if (!dateInput.value) {
        dateInput.value = new Date().toISOString().slice(0, 10); // تنظیم مقدار امروز
      }

      submitBtn.addEventListener('click', function () {
        console.log('asdasdads')
        var selectedDate = dateInput.value;
        var url = "/foodstuff/price/" + selectedDate + "/";
        window.location.href = url;
      });
    });
  </script>
  {% endblock %}