ehsan/ehsan/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings 

app_name='ehsan'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard, name='dashboard'),
    path('foodstuff/', include('foodstuff.urls')),
    path('repository/', include('repository.urls')),
    path('recipe/', include('recipe.urls')),
    path('record/', include('record.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    
    path('calendar', calendar, name='calendar'),
]


urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)  # media
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)  # static

ehsan/repository/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name='repository'

urlpatterns = [
    path('total-inventory/', TotalInventoryView, name='total_inventory'),
    path('in/<str:date>/', in_repository, name='in_repository'),
    path('out/<str:date>/', out_repository, name='out_repository'),

]

ehsan/repository/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.contrib.postgres.fields import JSONField
from django.utils import timezone


class Repository(models.Model):
    ENTRY_TYPES = (
        ('in', 'ورودی'),
        ('out', 'خروجی'),
    )

    id = ShortUUIDField(primary_key=True)
    date = models.DateField(default=timezone.now)
    type = models.CharField(max_length=3, choices=ENTRY_TYPES, default='in')
    quantities = models.JSONField(default=dict, null=True, blank=True)

    def __str__(self):
        return f"انبار روز {self.date} - {'ورودی' if self.type == 'in' else 'خروجی'}"

ehsan/repository/forms.py
from django import forms
from foodstuff.models import Stuffs


class RepositoryForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(RepositoryForm, self).__init__(*args, **kwargs)
        stuffs = Stuffs.objects.all()
        for stuff in stuffs:
            self.fields[f'stuff_{stuff.stuff_id}'] = forms.CharField(
                label=stuff.stuff_name, required=False, widget=forms.TextInput(attrs={'class': 'price-input'})
            )
    def clean(self):
        cleaned_data = super(RepositoryForm, self).clean()
        quantities = {}
        for field_name, value in cleaned_data.items():
            if field_name.startswith('stuff_'):
                stuff_id = field_name.split('_')[1]
                quantities[stuff_id] = value
        cleaned_data['quantities'] = quantities
        return cleaned_data

ehsan/repository/views.py
from django.shortcuts import render , redirect
from .models import Repository
from .forms import RepositoryForm
from datetime import datetime
from foodstuff.models import Stuffs,Category,Price
import jdatetime
from django.db.models import Max

def repository(request):
    return render(request, 'repository/repository.html')


def in_repository(request, date):
    gregorian_date = datetime.strptime(date, '%Y-%m-%d').date()  # تبدیل تاریخ به فرمت میلادی
    initial_type = 'in'

    repository_instance = None
    initial_data = None  # تعیین مقدار اولیه برای initial_data
    all_stuff_ids = Stuffs.objects.values_list('stuff_id', flat=True)

    if Repository.objects.filter(date=gregorian_date, type='in').exists():  # بررسی وجود رکورد
            repository_instance = Repository.objects.get(date=gregorian_date, type='in')
            initial_data = {'type': initial_type, **{'stuff_' + str(stuff_id): quantity for stuff_id, quantity in repository_instance.quantities.items()}}
            
    if request.method == 'POST':
        form = RepositoryForm(request.POST, initial=initial_data)
        if form.is_valid():
            quantities = form.cleaned_data['quantities']
            type = initial_type
            if repository_instance:
                repository_instance.quantities = quantities
                repository_instance.type = type
                repository_instance.save()
            else:
                repository_instance = Repository.objects.create(date=gregorian_date, type=type, quantities=quantities)
            today_date = datetime.now().strftime('%Y-%m-%d')
            return redirect(f'/repository/in/{today_date}/')
    else:
        initial_form_data = {'date': gregorian_date, 'type': initial_type}
        if initial_data:
            initial_form_data.update(initial_data)  # فقط اگر initial_data موجود باشد، آن را به initial_form_data اضافه کنید
        else:
            initial_data = {'type': initial_type,**{'stuff_' + str(stuff_id): 0 for stuff_id in all_stuff_ids}}
            initial_form_data.update(initial_data)  # فقط اگر initial_data موجود باشد، آن را به initial_form_data اضافه کنید
        form = RepositoryForm(initial=initial_form_data)  # استفاده از یک دیکشنری برای ارسال به عنوان initial
    
    jalali_date = jdatetime.date.fromgregorian(date=gregorian_date).strftime('%Y/%m/%d')
    categories = Category.objects.all().order_by('cat_id')  # اضافه کردن دسته بندی‌ها
    stuffs = Stuffs.objects.select_related('stuff_category').all()
    return render(request, 'repository/in_repository.html', {'form': form,'jalali_date':jalali_date ,'date': date, 'stuffs': stuffs, 'categories': categories})

def out_repository(request, date):
    gregorian_date = datetime.strptime(date, '%Y-%m-%d').date()  # تبدیل تاریخ به فرمت میلادی
    initial_type = 'out'
    all_stuff_ids = Stuffs.objects.values_list('stuff_id', flat=True)

    repository_instance = None
    initial_data = None

    if Repository.objects.filter(date=gregorian_date, type='out').exists():
        try:
            repository_instance = Repository.objects.get(date=gregorian_date, type='out')
            initial_data = {'type': initial_type, **{'stuff_' + str(stuff_id): quantity for stuff_id, quantity in repository_instance.quantities.items()}}
        except Repository.DoesNotExist:
            pass

    if request.method == 'POST':
        form = RepositoryForm(request.POST, initial=initial_data)
        if form.is_valid():
            quantities = form.cleaned_data['quantities']
            type = initial_type
            if repository_instance:
                repository_instance.quantities = quantities
                repository_instance.type = type
                repository_instance.save()
            else:
                repository_instance = Repository.objects.create(date=gregorian_date, type=type, quantities=quantities)
            today_date = datetime.now().strftime('%Y-%m-%d')
            return redirect(f'/repository/out/{today_date}/')
    else:
        initial_form_data = {'date': gregorian_date, 'type': initial_type}
        if initial_data:
            initial_form_data.update(initial_data)  # فقط اگر initial_data موجود باشد، آن را به initial_form_data اضافه کنید
        else:
            initial_data = {'type': initial_type,**{'stuff_' + str(stuff_id): 0 for stuff_id in all_stuff_ids}}
            initial_form_data.update(initial_data)  # فقط اگر initial_data موجود باشد، آن را به initial_form_data اضافه کنید
        form = RepositoryForm(initial=initial_form_data)  # استفاده از یک دیکشنری برای ارسال به عنوان initial
        
    jalali_date = jdatetime.date.fromgregorian(date=gregorian_date).strftime('%Y/%m/%d')
    categories = Category.objects.all().order_by('cat_id')  # اضافه کردن دسته بندی‌ها
    stuffs = Stuffs.objects.select_related('stuff_category').all()
    return render(request, 'repository/out_repository.html', {'form': form,'jalali_date':jalali_date,'date': date, 'stuffs': stuffs, 'categories': categories})

from django.http import HttpResponse
from .models import Repository

from django.shortcuts import render
from .models import Repository

def TotalInventoryView(request):
    # Define dictionaries to store the sum of quantities for each stuff_id for 'in' and 'out' types
    quantities_sum_in = {}
    quantities_sum_out = {}
    categories = Category.objects.all()  # اضافه کردن دسته بندی‌ها
    error_items = []  # لیستی برای نگهداری آیتم‌های دارای خطا

    # Get repositories with type 'in'
    repositories_in = Repository.objects.filter(type='in')
    
    # Get repositories with type 'out'
    repositories_out = Repository.objects.filter(type='out')
    
    # Function to accumulate quantities for each stuff_id
    def accumulate_quantities(repositories, quantities_sum):
        for repo in repositories:
            for stuff_id, quantity in repo.quantities.items():
                try:
                    # Remove commas from the quantity string and then convert to float
                    quantity = quantity.replace(',', '')
                    quantities_sum[stuff_id] = quantities_sum.get(stuff_id, 0) + float(quantity)
                except ValueError:
                    error_items.append({
                        'stuff_id': stuff_id,
                        'stuff_name': Stuffs.objects.get(stuff_id=stuff_id).stuff_name,
                        'date': repo.date
                    })
    
    # Accumulate quantities for 'in' type repositories
    accumulate_quantities(repositories_in, quantities_sum_in)
    
    # Accumulate quantities for 'out' type repositories
    accumulate_quantities(repositories_out, quantities_sum_out)
    
    # Calculate net sum of quantities for each stuff_id
    net_quantities = {}
    for stuff_id, sum_quantity_in in quantities_sum_in.items():
        sum_quantity_out = quantities_sum_out.get(stuff_id, 0)
        net_quantity = sum_quantity_in - sum_quantity_out
        net_quantities[stuff_id] = net_quantity

    # Prepare data for rendering
    data = []
    total_inventory_value = 0  # Initialize total inventory value

    for stuff_id, net_quantity in net_quantities.items():
        sum_quantity_in = quantities_sum_in.get(stuff_id, 0)
        sum_quantity_out = quantities_sum_out.get(stuff_id, 0)
        # Get stuff_name from the database
        stuff_name = Stuffs.objects.get(stuff_id=stuff_id).stuff_name  # Assuming you have a model for stuff
        stuff_category = Stuffs.objects.get(stuff_id=stuff_id).stuff_category  # Assuming you have a model for stuff
       
        # Fetch latest price for the stuff
        latest_price = Price.objects.filter(prices__has_key=stuff_id).aggregate(latest_date=Max('date'))
        if latest_price['latest_date']:
            latest_price_obj = Price.objects.get(date=latest_price['latest_date'])
            latest_price_value = latest_price_obj.prices.get(stuff_id, None)
            last_price = float(latest_price_value) * float(net_quantity)
        else:
            latest_price_value = 0
            last_price = 0

        total_inventory_value += last_price

        data.append({
            'stuff_id': stuff_id,
            'stuff_name': stuff_name,
            'stuff_category': stuff_category,
            'sum_quantity_in': sum_quantity_in,
            'sum_quantity_out': sum_quantity_out,
            'net_quantity': net_quantity,
            'latest_price': latest_price_value,
            'last_price':last_price
        })
    
    # Render the template with the data
    return render(request, 'repository/total_inventory.html', {
        'data': data,
        'categories': categories,
        'total_inventory_value': total_inventory_value,
        'error_items': error_items  # اضافه کردن لیست آیتم‌های دارای خطا به قالب
    })

ehsan/templates/repository/repository.html
{% extends 'main/main.html' %}
{% load static %}
{% block contant %}


{% endblock %}

ehsan/templates/repository/total_inventory.html
{% extends 'main/main.html' %}
{% load static %}
{% load humanizelib %}
{% block contant %}
<style>
    .small-td {
        width: 15%;
    }

    .th {
        background-color: #6CC3DA !important;
        color: white !important;
        font-size: 1vw !important;
        position: -webkit-sticky;
        position: sticky;
        top: 0;
        z-index: 2;
        text-align-last: center; 
        letter-spacing:0px !important;
        border:0px
    }
    .th span{
        font-size: 10px !important;
    }

    .table-responsive table {
        direction: rtl;
    }

    .search-container {
        display: inline-block;
        margin-left: 10px;
    }

    .form-control-sm {
        border-color: white !important;
    }
    .btn-arrow {
        background-color: #FF8A00;
        color: white;
        width: 1%;
        height: 1%;
        padding: 1%;
    }
    .bt-in {
        background-color: #c1e4ea;
        padding: 30px;
        margin-bottom: -30px;
        font-weight: bold;
        font-size: 1vw;
        border-top-left-radius: 15px;
        border-top-right-radius: 15px;
        border-bottom-left-radius: -15px;
        width: 100%;
        text-align: center;
    }

    .bt-in a {
        color: black !important;
    }

    .bt-out {
        padding: 30px;
        margin-bottom: -30px;
        font-weight: bold;
        font-size: 1vw;
        border-top-left-radius: 15px;
        border-top-right-radius: 15px;
        width: 100%;
        text-align: center;
    }

    .bt-out a {
        color: black !important;
    }

    #categoryFilter {
        margin-right: 20px;
    }

    .table-striped td {
        padding: 4px !important;
        /* Adjust the padding as needed */
        font-size: 0.8vw;
        /* Adjust the font size if needed */
    }

    .table-striped tr {
        line-height: 1.5vw !important;
        /* Reduce the line height */
    }
</style>
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold pt-3 mb-4">
        <span class="text-muted fw-light">انبار/</span> گزارش
        {% if error_items %}
        {{error_items}}
        {% endif %}
    </h4>
    <div class="row mb-4" style="justify-content: center;">
        <div class="col-md-4">
            <div class="bt-out">
                <a href="#" id="inputBtn">ورودی</a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="bt-out">
                <a href="#" id="outputBtn">خروجی</a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="bt-in">
                <a href="{% url 'repository:total_inventory' %}">گزارش موجودی</a>
            </div>
        </div>
    </div>
    <div class="card mb-4" style="background-color: #c1e4ea; box-shadow: none;margin-top:-20px">
        <div class="card-header" style="margin-inline: 60px;">
            <select id="categoryFilter" class="form-control-sm">
                <option value="">همه دسته بندی ها</option>
                {% for category in categories %}
                <option value="{{ category.cat_name }}" {% if category.id in selected_category %}selected{% endif %}>
                    {{ category.cat_name }}</option>
                {% endfor %}
            </select>
            <div id="datatable_filter" class="form-control-sm search-container">
                <input type="search" id="search-box" placeholder="جستجو" class="form-control form-control-sm">
            </div>
        </div>
        <div class="card-body">
            <div class="card mb-4" style="margin-inline: 60px; box-shadow: none;">
                <div class="card-body">
                    {% csrf_token %}
                    <input type="hidden" name="type" value="{{ form.initial.type }}">
                    <div class="table-responsive">
                        <table id="datatable" class="table table-striped text-center">
                            <thead class="table-light">
                                <tr>
                                    <th style="border-bottom-right-radius: 10px;
                                        border-top-right-radius: 10px; " class="th">دسته بندی</th>
                                    <th class="th">عنوان</th>
                                    <th class="th">موجودی</th>
                                    <th class="th">آخرین قیمت</th>
                                    <th style="border-bottom-left-radius: 10px;
                                        border-top-left-radius: 10px; " class="th">قیمت تمام شده</th>
                                    
                                </tr>
                            </thead>
                            <tbody id="table-body">
                                {% for item in data %}
                                <tr>
                                    <td class="small-td">{{ item.stuff_category }}</td>
                                    <td>{{ item.stuff_name }}</td>
                                    <td class="large-td" style="direction:ltr">{{ item.net_quantity|intcomma }}</td>
                                    <td class="larege" style="font-size: large;" style="direction:ltr">{{ item.latest_price|intcomma }}</td>
                                    <td class="larege" style="font-size: large;" style="direction:ltr">{{ item.last_price|intcomma }}</td>
                                </tr>
                                {% endfor %}
                                <tfoot>
                                    <td colspan="4" style="text-align:right;"><strong>مجموع ارزش انبار:</strong></td>
                                    <td><strong>{{ total_inventory_value|intcomma }}</strong></td>
                                </tfoot> 
                            </tbody>
                        </table>
                        <button class="btn btn-secondary mx-2" id="excelButton" style=" float: left;">اکسل</button>
                        <button class="btn btn-secondary" id="printButton" style=" float: left;">پرینت</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'vendor/js/jquery.min.js' %}"></script>

    <script src="{% static 'vendor/js/dataTables.min.js' %}"></script>

    <script>
        $(document).ready(function () {
            var table = $('#datatable').DataTable({
                paging: false,
                dom: 'lrtip', // remove the default search box
                buttons: [
                    {
                        extend: 'excel',
                        text: 'Excel',
                        className: 'custom-excel-button',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4], // Include columns except the last one
                            format: {
                                body: function (data, row, column, node) {
                                    if ($(node).find('input').length > 0) {
                                        return $(node).find('input').val(); // Use the input value instead of '1'
                                    }
                                    return data; // Use the default data if no input is found
                                }
                            }
                        }
                    },
                    {
                        extend: 'print',
                        text: 'Print',
                        className: 'custom-print-button',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4], // Include columns except the last one
                            format: {
                                body: function (data, row, column, node) {
                                    if ($(node).find('input').length > 0) {
                                        return $(node).find('input').val(); // Use the input value instead of '1'
                                    }
                                    return data; // Use the default data if no input is found
                                }
                            }
                        }
                    }
                ],
                fixedHeader: {
                    header: true,
                    footer: true
                },
                paging: false,
                scrollCollapse: true,
                scrollX: true,
                scrollY: 380
            });
            $('#categoryFilter').on('change', function () {
                var category = $(this).val();
                table.column(1).search(category).draw();
            });
            $('#search-box').on('keyup', function () {
                table.search(this.value).draw();
            });
            $('.dataTables_info').css('display', 'none');
            // Custom button click events
            $('#excelButton').on('click', function () {
                table.button('.custom-excel-button').trigger();
            });
            $('#printButton').on('click', function () {
                table.button('.custom-print-button').trigger();
            });

            // Hide default buttons
            $('.dt-buttons').hide();
        });
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // دریافت تاریخ امروز
            var today = new Date();
            var year = today.getFullYear();
            var month = ('0' + (today.getMonth() + 1)).slice(-2); // اضافه کردن صفر در صورت نیاز
            var day = ('0' + today.getDate()).slice(-2); // اضافه کردن صفر در صورت نیاز

            // ساختن تاریخ به فرمتی که مورد نیاز است
            var formattedDate = year + '-' + month + '-' + day;

            // ساختن URL جدید با تاریخ امروز
            var newUrlRepositoryout = '{% url "repository:out_repository" "PLACEHOLDER_DATE" %}'.replace('PLACEHOLDER_DATE', formattedDate);
            var newUrlRepositoryin = '{% url "repository:in_repository" "PLACEHOLDER_DATE" %}'.replace('PLACEHOLDER_DATE', formattedDate);

            // پیدا کردن المان لینک و به روزرسانی href آن
            var menuLinkRepositoryout = document.getElementById('outputBtn');
            var menuLinkRepositoryin = document.getElementById('inputBtn');

            if (menuLinkRepositoryout) {
                menuLinkRepositoryout.href = newUrlRepositoryout;
            }
            if (menuLinkRepositoryin) {
                menuLinkRepositoryin.href = newUrlRepositoryin;
            }
        });
    </script>
</div>
{% endblock %}